fix: allow one optimizer to be a prefix of another
google-research/federated pull request #3
Opened 2020-10-01 08:56 UTC by amitport

fix an issue when adding an optimizer with the same prefix as another. For example,
adding `adamW` will not work without this fix, because in a couple of places only the prefix is checked so the script will match as `adam`

2020-10-02 20:30 UTC, zcharles8 requested changes
Similar functionality is used in `utils/utils_impl.py`. Would you mind adding them to this change? Looks good by the way. Apologies for the duplication, there are subtle differences that are on my list to merge.

2020-10-03 05:13 UTC, amitport commented
> 
> 
> Similar functionality is used in `utils/utils_impl.py`. Would you mind adding them to this change? Looks good by the way. Apologies for the duplication, there are subtle differences that are on my list to merge.

done and rebased

2020-10-05 19:59 UTC, zcharles8 commented
@amitport Thanks! I'll submit this internally again (referencing your contribution).

2020-10-06 00:30 UTC, nightldj commented
Thanks @amitport and @zcharles8. Please move to ISSUES for more discussions. Thanks for the understanding.

2020-10-06 00:30 UTC, closed without merging

2020-10-07 15:43 UTC, zcharles8 commented
This change was included as part of 700cbc24a92575d761815895e845d9dbf608d677. Apologies for the lack of attribution; we faced some internal issues when pushing updates and had to merge the changes as one.